controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    joints:
      - l_wheel_joint
      - r_wheel_joint
      - l_caster_swivel_joint
      - r_caster_swivel_joint
      - l_caster_wheel_joint
      - r_caster_wheel_joint

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    
    # Tell controller to accept unstamped Twist messages
    use_stamped_vel: false
    
    left_wheel_names: ["l_wheel_joint"]
    right_wheel_names: ["r_wheel_joint"]
    
    wheel_separation: 0.4247
    wheel_radius: 0.04175
    
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    open_loop: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 2.0
        min_acceleration: -2.0
    
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        max_acceleration: 3.0
        min_acceleration: -3.0
